export const TABLE_COLUMN_CONFIG = {
    active_ingredients_moas: [
        { label: 'Id', value: 'id' },
        { label: 'Active Ingredient Root ID', value: 'active_ingredient_root_id' },
        { label: 'Active Ingredient Name', value: 'active_ingredient_root_name' },
        { label: 'Mechanism of Action', value: 'mechanism_of_action' },
        { label: 'Verification Status', value: 'verification_status' },
    ],
    active_ingredients_drug_classes: [
        { label: 'Id', value: 'id' },
        { label: 'Active Ingredient Root ID', value: 'active_ingredient_root_id' },
        { label: 'Active Ingredient Name', value: 'active_ingredient_root_name' },
        { label: 'Drug Class Root ID', value: 'drug_class_root_id' },
        { label: 'Drug Class Name', value: 'drug_class_root_name' },
        { label: 'Verification Status', value: 'verification_status' },
    ],
    active_ingredients_targets: [
        { label: 'Id', value: 'id' },
        { label: 'Active Ingredient Root ID', value: 'active_ingredient_root_id' },
        { label: 'Active Ingredient Name', value: 'active_ingredient_root_name' },
        { label: 'Target Root ID', value: 'target_root_id' },
        { label: 'Target Name', value: 'target_root_name' },
        { label: 'Verification Status', value: 'verification_status' },
    ],
    diseases_studies: [
        { label: 'Id', value: 'id' },
        { label: 'NCT ID', value: 'nct_id' },
        { label: 'Indication', value: 'indication' },
        { label: 'Disease Root ID', value: 'disease_root_id' },
        { label: 'Disease Name', value: 'disease_root_name' },
        { label: 'Verification Status', value: 'verification_status' },
    ],
    drug_classes_targets: [
        { label: 'Id', value: 'id' },
        { label: 'Drug Class Root ID', value: 'drug_class_root_id' },
        { label: 'Drug Class Name', value: 'drug_class_root_name' },
        { label: 'Target Root ID', value: 'target_root_id' },
        { label: 'Target Name', value: 'target_root_name' },
        { label: 'Verification Status', value: 'verification_status' },
    ],
    drugs_sales: [
        { label: 'Id', value: 'id' },
        { label: 'Brand Root ID', value: 'brand_root_id' },
        { label: 'Brand Name', value: 'brand_root_name' },
        { label: 'Organization Root ID', value: 'organization_root_id' },
        { label: 'Organization Name', value: 'organization_root_name' },
    ],
    drugs_studies: [
        { label: 'Id', value: 'id' },
        { label: 'NCT ID', value: 'nct_id' },
        { label: 'Active Ingredient Root ID', value: 'active_ingredient_root_id' },
        { label: 'Active Ingredient Name', value: 'active_ingredient_root_name' },
        { label: 'Brand Root ID', value: 'brand_root_id' },
        { label: 'Brand Name', value: 'brand_root_name' },
        { label: 'Drug Class Root ID', value: 'drug_class_root_id' },
        { label: 'Drug Class Name', value: 'drug_class_root_name' },
        { label: 'Target Root ID', value: 'target_root_id' },
        { label: 'Target Name', value: 'target_root_name' },
        { label: 'Owner Organization Root ID', value: 'owner_organization_root_id' },
        { label: 'Owner Organization Name', value: 'organization_root_name' },
        { label: 'Drug Type', value: 'drug_type' },
        { label: 'Verification Status', value: 'verification_status' },
    ],
    organizations: [
        { label: 'Id', value: 'id' },
        { label: 'Organization Root ID', value: 'organization_root_id' },
        { label: 'organization Name', value: 'organization_root_name' },
        { label: 'Type', value: 'type' },
        { label: 'Is Active', value: 'is_active' },
        { label: 'Size', value: 'size' },
        { label: 'Stage', value: 'stage' },
        { label: 'Is Public', value: 'is_public' },
        { label: 'Website', value: 'website' },
        { label: 'Pipeline URL', value: 'pipeline_url' },
        { label: 'Market Cap Currency', value: 'market_capital_currency' },
        { label: 'Market Cap', value: 'market_capital' },
    ],
    organizations_studies: [
        { label: 'Id', value: 'id' },
        { label: 'NCT ID', value: 'nct_id' },
        { label: 'Organization Root ID', value: 'organization_root_id' },
        { label: 'Organization Name', value: 'organization_root_name' },
        { label: 'Organization Role', value: 'organization_role' },
        { label: 'Verification Status', value: 'verification_status' },
    ],
    roots: [
        { label: 'Id', value: 'id' },
        { label: 'Name', value: 'name' },
        { label: 'Label', value: 'label' },
        { label: 'Case Insensitive', value: 'is_case_sensitive' },
        { label: 'Meta Data Verified', value: 'is_meta_data_verified' },
        { label: 'Verification Status', value: 'verification_status' },
    ],
    relationships: [
        { label: 'Id', value: 'id' },
        { label: 'Parent Root ID', value: 'parent_root_id' },
        { label: 'Parent Name', value: 'parent_root_name' },
        { label: 'Child Root ID', value: 'child_root_id' },
        { label: 'Child Root Name', value: 'child_root_name' },
        { label: 'Relationship', value: 'relationship' },
        { label: 'Verification Status', value: 'verification_status' },
    ],
    synonyms: [
        { label: 'Id', value: 'id' },
        { label: 'Root ID', value: 'root_id' },
        { label: 'Root Name', value: 'root_name' },
        { label: 'Synonym Name', value: 'name' },
        { label: 'Generated', value: 'is_generated' },
        { label: 'Case Insensitive', value: 'is_case_sensitive' },
        { label: 'Verification Status', value: 'verification_status' },
    ],
    trials: [
        { label: 'NCT ID', value: 'nct_id' },
        { label: 'Acronym', value: 'acronym' },
        { label: 'Brief Title', value: 'brief_title' },
        { label: 'Official Title', value: 'official_title' },
        { label: 'Phases', value: 'phases' },
        { label: 'Study Start Date', value: 'study_start_date' },
        { label: 'Study Completion Date', value: 'study_completion_date' },
        { label: 'Overall Status', value: 'overall_status' },
        { label: 'Verification Status', value: 'verification_status' },
    ],
    organizations_financials: [
        { label: 'Id', value: 'id' },
        { label: 'Organization Root ID', value: 'organization_root_id' },
        { label: 'Organization Name', value: 'organization_root_name' },
        { label: 'Category ID', value: 'category_id' },
        { label: 'Value', value: 'value' },
        { label: 'Raw Value', value: 'raw_value' },
        { label: 'Currency', value: 'currency' },
        { label: 'Frequency', value: 'frequency' },
        { label: 'Time Period', value: 'time_period' },
        { label: 'Status', value: 'status' },
    ],
    organizations_stock_history: [
        { label: 'Id', value: 'id' },
        { label: 'Organization Root ID', value: 'organization_root_id' },
        { label: 'Organization Name', value: 'organization_root_name' },
        { label: 'Previous Close', value: 'previous_close' },
        { label: 'Market Cap', value: 'market_cap' },
        { label: 'Currency', value: 'currency' },
        { label: 'Closing Date', value: 'closing_date' },
    ],
    readouts: [
        { label: 'Id', value: 'id' },
        { label: 'Entity ID', value: 'entity_id' },
        { label: 'Source Type', value: 'source_type' },
        { label: 'Category', value: 'category' },
        { label: 'Results Stage', value: 'results_stage' },
        { label: 'Results Stage Root ID', value: 'results_stage_root_id' },
        { label: 'Results Stage Root Name', value: 'results_stage_root_name' },
        { label: 'Verification Status', value: 'verification_status' },
    ],
};
